add several hooks availables at cluser setup

diff --git a/libexec/pgenv--cluster-functions b/libexec/pgenv--cluster-functions
--- a/libexec/pgenv--cluster-functions
+++ b/libexec/pgenv--cluster-functions
@@ -497,6 +497,7 @@ start_instance_safely() {
   local instance="$(get_instance "$instance_name")"
   shift
   local start_options="$@"
+  local status=
 
   if [ -z "$instance" ]; then
     log_warn "$(self -v): invalid instance: $instance_name"
@@ -512,8 +513,22 @@ start_instance_safely() {
       (
         cd "$PGENV_CLUSTER_ROOT"
         eval "$(switch_context && pwd)/bin/pg_ctl" -D "$instance_name" start $start_options
-      )
-      start_instance_safely "$node" "$start_options"
+      ) || status=$?
+
+      if [ $status -eq 0 ]; then
+        # callback
+        if [ "$instance_name" = "$primary_server" ]; then
+          on_primary_started
+        else
+          on_standby_started "${instance_name}"
+        fi
+
+        # Enter next replication tree.
+        start_instance_safely "$node" "$start_options"
+      else
+        log_warn "failed to start instance: $standby_server"
+        break
+      fi
     fi
   done
 }
@@ -530,6 +545,9 @@ start_all_instances() {
     start_instance "$primary_server" || status=$?
     if [ $status -ne 0 ]; then
       log_warn "server may be already running: $primary_server"
+    else
+      # callback
+      on_primary_started
     fi
 
     local instance=
@@ -538,6 +556,9 @@ start_all_instances() {
       start_instance "$instance" || status=$?
       if [ $status -ne 0 ]; then
         log_warn "instance may be already running: $instance"
+      else
+        # callback
+        on_standby_started "${instance}"
       fi
     done
   }
@@ -632,7 +653,10 @@ attach_node() {
 
   (
     cd "$PGENV_CLUSTER_ROOT"
-    local archive_dir="$(resolve_link archivedir_${new_node})"
+    declare -r archive_dir="$(resolve_link archivedir_${new_node})"
+    declare -r include_file="$(resolve_link ${new_node}.conf)"
+    declare -r port="$pg_start_port"
+    declare -r pgdata="$PGENV_CLUSTER_ROOT/${new_node}"
 
     if [ -d "$new_node" ]; then
       error "error: directory already exists: $new_node"
@@ -647,38 +671,26 @@ attach_node() {
       exit 1
     fi
 
-    local include_file="$(resolve_link ${new_node}.conf)"
-    local port="$pg_start_port"
     # Create include file for standby
     log_info "create include file for standby: $include_file"
 
-    cat <<EOF > "$include_file"
-port = $port
-wal_keep_segments = 16
-hot_standby = on
-logging_collector = on
-log_filename = 'postgresql-%Y-%m-%d.log'
-#log_min_messages = warning
-max_wal_senders = $((10 + $standby_num))
-wal_level = logical
-archive_mode = always
-archive_command = 'cp %p "$archive_dir/%f"'
-EOF
+    # Call callback function
+    log_trace "call on_standby_setup"
+    on_standby_setup "${new_node}"
+
     # Set include file (to overwrite settings)
     replace_string_in_file "del" "$new_node/postgresql.conf" \
                            "include = " "include = '$include_file'"
 
+    local recovery_conf="${new_node}/recovery.conf"
     if version_later_than 12 &> /dev/null; then
-      cat <<EOF >> "$new_node.conf"
-recovery_target_timeline = 'latest'
-#restore_command = 'cp "$(resolve_link "$archive_dir")/%f" "%p"'
-EOF
-    else
-      cat <<EOF >> "$new_node/recovery.conf"
-recovery_target_timeline = 'latest'
-#restore_command = 'cp "$(resolve_link "$archive_dir")/%f" "%p"'
-EOF
+      recovery_conf="${new_node}.conf"
     fi
+
+    # Call callback function
+    log_trace "call on_standby_recovery_setup"
+    on_standby_recovery_setup "${new_node}"
+
     mkdir -p "$archive_dir"
   )
 
@@ -758,9 +770,15 @@ start_cluster() {
   log_info "==> start cluster: $PGENV_CLUSTER_ROOT"
   start_instance "$primary_server"
 
+  # callback
+  on_primary_started
+
   local instance=
   for instance in ${all_standby_servers[@]:-}; do
     start_instance "$instance"
+
+    log_trace "call on_standby_started"
+    on_standby_started "${instance}"
   done
 }
 
diff --git a/libexec/pgenv-exec-cluster-setup b/libexec/pgenv-exec-cluster-setup
--- a/libexec/pgenv-exec-cluster-setup
+++ b/libexec/pgenv-exec-cluster-setup
@@ -4,6 +4,8 @@ set -eu
 
 source "$PGENV_LIBEXEC"/pgenv--load
 source "$PGENV_LIBEXEC"/pgenv--cluster-functions
+load pgenv--cluster-callback
+load_if_exists "pgenv-cluster-callback.sh" ||:
 
 
 # Command line options
@@ -212,26 +214,16 @@ setup_cluster() {
 
   (
     cd "$PGENV_CLUSTER_ROOT"
-    local archive_dir="$(resolve_link archivedir_${primary_server})"
-    local include_file="$(resolve_link "${primary_server}.conf")"
+    declare -r archive_dir="$(resolve_link archivedir_${primary_server})"
+    declare -r include_file="$(resolve_link "${primary_server}.conf")"
+    declare -r port="$primary_port"
+    declare -r pgdata="$PGENV_CLUSTER_ROOT/${primary_server}"
 
     # Create include file for primary
     log_info "create include file for primary: $include_file"
-    cat <<EOF > "$include_file"
-port = $primary_port
-max_wal_senders = $((10 + $standby_num))
-wal_keep_segments = 16
-wal_level = logical
-archive_mode = on
-archive_command = 'test ! -f "$archive_dir/%f" && cp %p "$archive_dir/%f"'
-logging_collector = on
-#log_min_messages = warning
-log_filename = 'postgresql-%Y-%m-%d.log'
-#log_statement = 'none'			# none, ddl, mod, all
-log_checkpoints = on
-synchronous_standby_names = '$(join_strings "," "${synchronous_standby_servers[@]}")'
-hot_standby = on
-EOF
+
+    # callback
+    on_primary_setup
 
     # Set include file (to overwrite settings)
     replace_string_in_file "del" "$primary_server/postgresql.conf" \
@@ -249,6 +241,9 @@ EOF
 
   log_info "start primary instance"
   start_instance "$primary_server"
+
+  # callback
+  on_primary_started
 
   #
   # Setup standby servers
@@ -271,47 +266,41 @@ EOF
     local pgver=$(current_pg_version)
     (
       cd "$PGENV_CLUSTER_ROOT"
-      local archive_dir="$(resolve_link archivedir_${standby_server})"
-      local include_file="$(resolve_link ${standby_server}.conf)"
-      local port="$pg_start_port"
+      declare -r archive_dir="$(resolve_link archivedir_${standby_server})"
+      declare -r include_file="$(resolve_link ${standby_server}.conf)"
+      declare -r port="$standby_port"
+      declare -r pgdata="$PGENV_CLUSTER_ROOT/${standby_server}"
+
       # Create include file for standby
       log_info "create include file for standby: $include_file"
 
-      cat <<EOF > "$include_file"
-port = $standby_port
-wal_keep_segments = 16
-hot_standby = on
-logging_collector = on
-log_filename = 'postgresql-%Y-%m-%d.log'
-#log_min_messages = warning
-max_wal_senders = $((10 + $standby_num))
-wal_level = logical
-archive_mode = always
-archive_command = 'cp %p "$archive_dir/%f"'
-EOF
+      # Call callback function
+      on_standby_setup "${standby_server}"
+
       # Set include file (to overwrite settings)
       replace_string_in_file "del" "$standby_server/postgresql.conf" \
                              "include = " "include = '$include_file'"
 
+      local recovery_conf="${standby_server}/recovery.conf"
       if version_later_than 12 &> /dev/null; then
-        cat <<EOF >> "${standby_server}.conf"
-recovery_target_timeline = 'latest'
-#restore_command = 'cp "$(resolve_link "$archive_dir")/%f" "%p"'
-EOF
-      else
-        cat <<EOF >> "$standby_server/recovery.conf"
-recovery_target_timeline = 'latest'
-#restore_command = 'cp "$(resolve_link "$archive_dir")/%f" "%p"'
-EOF
+        recovery_conf="${standby_server}.conf"
       fi
+
+      # callback
+      on_standby_recovery_setup "${standby_server}"
+
       mkdir -p "$archive_dir"
     )
 
     log_info "start standby instance"
     status=0
     start_instance "$standby_server" || status=$?
+
     if [ $status -ne 0 ]; then
-      log_warn "failed start instance: $standby_server"
+      log_warn "failed to start instance: $standby_server"
+    else
+      # callback
+      on_standby_started "${standby_server}"
     fi
   done
 }
